# Generated by Django 3.2.7 on 2021-10-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20211020_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day_of_task',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
