# Generated by Django 3.2.7 on 2021-10-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_task_day_of_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day_of_task',
        ),
    ]
