# Generated by Django 3.2.8 on 2021-10-21 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_task_day_of_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaystask',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todaystask',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
