# Generated by Django 3.2.8 on 2021-10-22 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0007_auto_20211021_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhockTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('section', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=20)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_completed', models.DateTimeField(null=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
