# Generated by Django 3.2.7 on 2021-09-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210923_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdms_issue', models.CharField(max_length=10)),
                ('trilogi_issue', models.CharField(max_length=10)),
                ('tdss_issue', models.CharField(max_length=10)),
            ],
        ),
    ]
