# Generated by Django 3.2.7 on 2021-09-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_smt_day_of_weekly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
