# Generated by Django 3.2.7 on 2021-09-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_delete_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='smt',
            name='notes',
            field=models.TextField(default='No notes here at the moment'),
            preserve_default=False,
        ),
    ]
