# Generated by Django 3.2.8 on 2022-09-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_smt_notes'),
    ]

    operations = [
        migrations.RenameModel('Smt', 'DSS')
    ]
