# Generated by Django 3.2.8 on 2022-09-24 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20220918_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('stage_title', models.TextField()),
                ('stage_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_id', models.IntegerField()),
                ('dss_in_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.dss')),
            ],
        ),
        migrations.CreateModel(
            name='DatesOfBuildStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('build_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.inbuild')),
                ('build_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.buildstages')),
            ],
        ),
    ]
