# Generated by Django 3.2.8 on 2022-09-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_buildstages_datesofbuildstages_inbuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildstages',
            name='exp_comp_time',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
