# Generated by Django 3.2.8 on 2022-09-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_buildstages_exp_comp_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbuild',
            name='build_id',
        ),
    ]
