# Generated by Django 3.2.8 on 2022-10-06 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_remove_inbuild_build_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbuild',
            name='start_date_of_build',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
